#!/bin/bash

if [[ $CYPRESS_BRB =~ \b(?:staging|schulportal)\b && $CYPRESS_NBC =~ \b(?:staging|schulportal)\b && $CYPRESS_DEFAULT =~ \b(?:staging|schulportal)\b ]]; then
  echo "Loading staging environment variables"
  ENV_PREFIX="ref"
else
  echo "Loading dev environment variables"
  ENV_PREFIX="dev"
fi

# Define your environment variables
declare -a env_vars=(
  "CYPRESS_TEACHER_1_BRB_EMAIL"
  "CYPRESS_TEACHER_1_BRB_PASSWORD"
  "CYPRESS_TEACHER_1_BRB_FIRST_NAME"
  "CYPRESS_TEACHER_1_BRB_LAST_NAME"
  "CYPRESS_TEACHER_2_BRB_EMAIL"
  "CYPRESS_TEACHER_2_BRB_PASSWORD"
  "CYPRESS_TEACHER_2_BRB_FIRST_NAME"
  "CYPRESS_TEACHER_2_BRB_LAST_NAME"
  "CYPRESS_TEACHER_1_DBC_EMAIL"
  "CYPRESS_TEACHER_1_DBC_PASSWORD"
  "CYPRESS_TEACHER_1_DBC_FIRST_NAME"
  "CYPRESS_TEACHER_1_DBC_LAST_NAME"
  "CYPRESS_TEACHER_2_DBC_EMAIL"
  "CYPRESS_TEACHER_2_DBC_PASSWORD"
  "CYPRESS_TEACHER_2_DBC_FIRST_NAME"
  "CYPRESS_TEACHER_2_DBC_LAST_NAME"
  "CYPRESS_TEACHER_1_NBC_EMAIL"
  "CYPRESS_TEACHER_1_NBC_PASSWORD"
  "CYPRESS_TEACHER_1_NBC_FIRST_NAME"
  "CYPRESS_TEACHER_1_NBC_LAST_NAME"
  "CYPRESS_TEACHER_2_NBC_EMAIL"
  "CYPRESS_TEACHER_2_NBC_PASSWORD"
  "CYPRESS_TEACHER_2_NBC_FIRST_NAME"
  "CYPRESS_TEACHER_2_NBC_LAST_NAME"
  "CYPRESS_STUDENT_1_BRB_EMAIL"
  "CYPRESS_STUDENT_1_BRB_PASSWORD"
  "CYPRESS_STUDENT_2_BRB_EMAIL"
  "CYPRESS_STUDENT_2_BRB_PASSWORD"
  "CYPRESS_STUDENT_1_DBC_EMAIL"
  "CYPRESS_STUDENT_1_DBC_PASSWORD"
  "CYPRESS_STUDENT_2_DBC_EMAIL"
  "CYPRESS_STUDENT_2_DBC_PASSWORD"
  "CYPRESS_STUDENT_1_NBC_EMAIL"
  "CYPRESS_STUDENT_1_NBC_PASSWORD"
  "CYPRESS_STUDENT_2_NBC_EMAIL"
  "CYPRESS_STUDENT_2_NBC_PASSWORD"
  "CYPRESS_ADMIN_1_BRB_EMAIL"
  "CYPRESS_ADMIN_1_BRB_PASSWORD"
  "CYPRESS_ADMIN_1_DBC_EMAIL"
  "CYPRESS_ADMIN_1_DBC_PASSWORD"
  "CYPRESS_ADMIN_1_NBC_EMAIL"
  "CYPRESS_ADMIN_1_NBC_PASSWORD"
  "CYPRESS_EXPERT_1_BRB_EMAIL"
  "CYPRESS_EXPERT_1_BRB_PASSWORD"
  "CYPRESS_EXPERT_1_DBC_EMAIL"
  "CYPRESS_EXPERT_1_DBC_PASSWORD"
  "CYPRESS_EXPERT_1_NBC_EMAIL"
  "CYPRESS_EXPERT_1_NBC_PASSWORD"
  "CYPRESS_STUDENT_BRB_EXTERN"
  "CYPRESS_STUDENT_BRB_EXTERN_PASSWORD"
  "CYPRESS_STUDENT_DBC_EXTERN"
  "CYPRESS_STUDENT_DBC_EXTERN_PASSWORD"
  "CYPRESS_STUDENT_NBC_EXTERN"
  "CYPRESS_STUDENT_NBC_EXTERN_PASSWORD"
  "CYPRESS_STUDENT_BRB_PASSWORD_CHANGE_EMAIL"
  "CYPRESS_STUDENT_BRB_PASSWORD_CHANGE_OLD_PWD"
  "CYPRESS_STUDENT_BRB_PASSWORD_CHANGE_NEW_PWD"
  "CYPRESS_STUDENT_DBC_PASSWORD_CHANGE_EMAIL"
  "CYPRESS_STUDENT_DBC_PASSWORD_CHANGE_OLD_PWD"
  "CYPRESS_STUDENT_DBC_PASSWORD_CHANGE_NEW_PWD"
  "CYPRESS_STUDENT_NBC_PASSWORD_CHANGE_EMAIL"
  "CYPRESS_STUDENT_NBC_PASSWORD_CHANGE_OLD_PWD"
  "CYPRESS_STUDENT_NBC_PASSWORD_CHANGE_NEW_PWD"
)

# Loop through and set environment variables
for var in "${env_vars[@]}"; do
  if [[ $var == *"_NBC_"* ]]; then
    ENV="nbc"
    echo "Setting ${var}=${ENV_PREFIX}:${var}"
    echo "${var}=op://cy-${ENV_PREFIX}-${ENV}/cypress/${var}" >> $GITHUB_ENV
  elif [[ $var == *"_BRB_"* ]]; then
    ENV="brb"
    echo "Setting ${var}=${ENV_PREFIX}:${var}"
    echo "${var}=op://cy-${ENV_PREFIX}-${ENV}/cypress/${var}" >> $GITHUB_ENV
  else
    ENV="dbc"
    echo "Setting ${var}=${ENV_PREFIX}:${var}"
    echo "${var}=op://cy-${ENV_PREFIX}-${ENV}/cypress/${var}" >> $GITHUB_ENV
  fi

done
