name: e2e-scheduled-trigger-tests
on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  e2e-system-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set all parameters for next job
        id: set_variables
        shell: bash
        run: |

          if [[ ! ${{ inputs.instance1 }} =~ (staging|schulportal) && ! ${{ inputs.instance2 }} =~ (staging|schulportal) && ! ${{ inputs.instance3 }} =~ (staging|schulportal) ]]; then
              echo "environment=dev" >> $GITHUB_OUTPUT
          else
              echo "environment=ref" >> $GITHUB_OUTPUT
          fi

  run-tests-groupA:
    needs: e2e-system-tests
    uses: ./.github/workflows/main.yml
    secrets:
      service-account-token: ${{ secrets.CYPRESS_ONEPWD_SERVICE_ACCOUNT_TOKEN }}
    with:
      cypress_brb: ${{ inputs.instance1 }}
      cypress_dbc: ${{ inputs.instance3 }}
      cypress_nbc: ${{ inputs.instance2 }}
      tag: cy:headless:stable:groupA:school_api_test:ci
      environment: ${{ needs.e2e-system-tests.outputs.environment }}
      groups: group-A

  run-tests-groupB:
    needs: e2e-system-tests
    uses: ./.github/workflows/main.yml
    secrets:
      service-account-token: ${{ secrets.CYPRESS_ONEPWD_SERVICE_ACCOUNT_TOKEN }}
    with:
      cypress_brb: ${{ inputs.instance1 }}
      cypress_dbc: ${{ inputs.instance3 }}
      cypress_nbc: ${{ inputs.instance2 }}
      tag: cy:headless:stable:groupB:school_api_test:ci
      environment: ${{ needs.e2e-system-tests.outputs.environment }}
      groups: group-B

  run-tests-groupC:
    needs: e2e-system-tests
    uses: ./.github/workflows/main.yml
    secrets:
      service-account-token: ${{ secrets.CYPRESS_ONEPWD_SERVICE_ACCOUNT_TOKEN }}
    with:
      cypress_brb: ${{ inputs.instance1 }}
      cypress_dbc: ${{ inputs.instance3 }}
      cypress_nbc: ${{ inputs.instance2 }}
      tag: cy:headless:stable:groupC:school_api_test:ci
      environment: ${{ needs.e2e-system-tests.outputs.environment }}
      groups: group-C

  run-tests-groupD:
    needs: e2e-system-tests
    uses: ./.github/workflows/main.yml
    secrets:
      service-account-token: ${{ secrets.CYPRESS_ONEPWD_SERVICE_ACCOUNT_TOKEN }}
    with:
      cypress_brb: ${{ inputs.instance1 }}
      cypress_dbc: ${{ inputs.instance3 }}
      cypress_nbc: ${{ inputs.instance2 }}
      tag: cy:headless:stable:groupD:school_api_test:ci
      environment: ${{ needs.e2e-system-tests.outputs.environment }}
      groups: group-D

  run-tests-groupE:
    needs: e2e-system-tests
    uses: ./.github/workflows/main.yml
    secrets:
      service-account-token: ${{ secrets.CYPRESS_ONEPWD_SERVICE_ACCOUNT_TOKEN }}
    with:
      cypress_brb: ${{ inputs.instance1 }}
      cypress_dbc: ${{ inputs.instance3 }}
      cypress_nbc: ${{ inputs.instance2 }}
      tag: cy:headless:stable:groupE:school_api_test:ci
      environment: ${{ needs.e2e-system-tests.outputs.environment }}
      groups: group-E

  run-tests-groupF:
    needs: e2e-system-tests
    uses: ./.github/workflows/main.yml
    secrets:
      service-account-token: ${{ secrets.CYPRESS_ONEPWD_SERVICE_ACCOUNT_TOKEN }}
    with:
      cypress_brb: ${{ inputs.instance1 }}
      cypress_dbc: ${{ inputs.instance3 }}
      cypress_nbc: ${{ inputs.instance2 }}
      tag: cy:headless:stable:groupF:school_api_test:ci
      environment: ${{ needs.e2e-system-tests.outputs.environment }}
      groups: group-F

  run-tests-groupG:
    needs: e2e-system-tests
    uses: ./.github/workflows/main.yml
    secrets:
      service-account-token: ${{ secrets.CYPRESS_ONEPWD_SERVICE_ACCOUNT_TOKEN }}
    with:
      cypress_brb: ${{ inputs.instance1 }}
      cypress_dbc: ${{ inputs.instance3 }}
      cypress_nbc: ${{ inputs.instance2 }}
      tag: cy:headless:stable:groupG:school_api_test:ci
      environment: ${{ needs.e2e-system-tests.outputs.environment }}
      groups: group-G

  run-tests-groupH:
    needs: e2e-system-tests
    uses: ./.github/workflows/main.yml
    secrets:
      service-account-token: ${{ secrets.CYPRESS_ONEPWD_SERVICE_ACCOUNT_TOKEN }}
    with:
      cypress_brb: ${{ inputs.instance1 }}
      cypress_dbc: ${{ inputs.instance3 }}
      cypress_nbc: ${{ inputs.instance2 }}
      tag: cy:headless:stable:groupH:school_api_test:ci
      environment: ${{ needs.e2e-system-tests.outputs.environment }}
      groups: group-H

  run-tests-groupI:
    needs: e2e-system-tests
    uses: ./.github/workflows/main.yml
    secrets:
      service-account-token: ${{ secrets.CYPRESS_ONEPWD_SERVICE_ACCOUNT_TOKEN }}
    with:
      cypress_brb: ${{ inputs.instance1 }}
      cypress_dbc: ${{ inputs.instance3 }}
      cypress_nbc: ${{ inputs.instance2 }}
      tag: cy:headless:stable:groupI:school_api_test:ci
      environment: ${{ needs.e2e-system-tests.outputs.environment }}
      groups: group-I

  run-tests-groupJ:
    needs: e2e-system-tests
    uses: ./.github/workflows/main.yml
    secrets:
      service-account-token: ${{ secrets.CYPRESS_ONEPWD_SERVICE_ACCOUNT_TOKEN }}
    with:
      cypress_brb: ${{ inputs.instance1 }}
      cypress_dbc: ${{ inputs.instance3 }}
      cypress_nbc: ${{ inputs.instance2 }}
      tag: cy:headless:stable:groupJ:school_api_test:ci
      environment: ${{ needs.e2e-system-tests.outputs.environment }}
      groups: group-J

  run-tests-groupK:
    needs: e2e-system-tests
    uses: ./.github/workflows/main.yml
    secrets:
      service-account-token: ${{ secrets.CYPRESS_ONEPWD_SERVICE_ACCOUNT_TOKEN }}
    with:
      cypress_brb: ${{ inputs.instance1 }}
      cypress_dbc: ${{ inputs.instance3 }}
      cypress_nbc: ${{ inputs.instance2 }}
      tag: cy:headless:stable:groupK:school_api_test:ci
      environment: ${{ needs.e2e-system-tests.outputs.environment }}
      groups: group-K

  run-tests-groupL:
    needs: e2e-system-tests
    uses: ./.github/workflows/main.yml
    secrets:
      service-account-token: ${{ secrets.CYPRESS_ONEPWD_SERVICE_ACCOUNT_TOKEN }}
    with:
      cypress_brb: ${{ inputs.instance1 }}
      cypress_dbc: ${{ inputs.instance3 }}
      cypress_nbc: ${{ inputs.instance2 }}
      tag: cy:headless:stable:groupL:school_api_test:ci
      environment: ${{ needs.e2e-system-tests.outputs.environment }}
      groups: group-L

  run-tests-groupM:
    needs: e2e-system-tests
    uses: ./.github/workflows/main.yml
    secrets:
      service-account-token: ${{ secrets.CYPRESS_ONEPWD_SERVICE_ACCOUNT_TOKEN }}
    with:
      cypress_brb: ${{ inputs.instance1 }}
      cypress_dbc: ${{ inputs.instance3 }}
      cypress_nbc: ${{ inputs.instance2 }}
      tag: cy:headless:stable:groupM:school_api_test:ci
      environment: ${{ needs.e2e-system-tests.outputs.environment }}
      groups: group-M

  run-tests-groupN:
    needs: e2e-system-tests
    uses: ./.github/workflows/main.yml
    secrets:
      service-account-token: ${{ secrets.CYPRESS_ONEPWD_SERVICE_ACCOUNT_TOKEN }}
    with:
      cypress_brb: ${{ inputs.instance1 }}
      cypress_dbc: ${{ inputs.instance3 }}
      cypress_nbc: ${{ inputs.instance2 }}
      tag: cy:headless:stable:groupN:school_api_test:ci
      environment: ${{ needs.e2e-system-tests.outputs.environment }}
      groups: group-N

  run-tests-groupO:
    needs: e2e-system-tests
    uses: ./.github/workflows/main.yml
    secrets:
      service-account-token: ${{ secrets.CYPRESS_ONEPWD_SERVICE_ACCOUNT_TOKEN }}
    with:
      cypress_brb: ${{ inputs.instance1 }}
      cypress_dbc: ${{ inputs.instance3 }}
      cypress_nbc: ${{ inputs.instance2 }}
      tag: cy:headless:stable:groupO:school_api_test:ci
      environment: ${{ needs.e2e-system-tests.outputs.environment }}
      groups: group-O

  run-tests-groupP:
    needs: e2e-system-tests
    uses: ./.github/workflows/main.yml
    secrets:
      service-account-token: ${{ secrets.CYPRESS_ONEPWD_SERVICE_ACCOUNT_TOKEN }}
    with:
      cypress_brb: ${{ inputs.instance1 }}
      cypress_dbc: ${{ inputs.instance3 }}
      cypress_nbc: ${{ inputs.instance2 }}
      tag: cy:headless:stable:groupP:school_api_test:ci
      environment: ${{ needs.e2e-system-tests.outputs.environment }}
      groups: group-P

  run-tests-groupQ:
    needs: e2e-system-tests
    uses: ./.github/workflows/main.yml
    secrets:
      service-account-token: ${{ secrets.CYPRESS_ONEPWD_SERVICE_ACCOUNT_TOKEN }}
    with:
      cypress_brb: ${{ inputs.instance1 }}
      cypress_dbc: ${{ inputs.instance3 }}
      cypress_nbc: ${{ inputs.instance2 }}
      tag: cy:headless:stable:groupQ:school_api_test:ci
      environment: ${{ needs.e2e-system-tests.outputs.environment }}
      groups: group-Q

  run-tests-groupR:
    needs: e2e-system-tests
    uses: ./.github/workflows/main.yml
    secrets:
      service-account-token: ${{ secrets.CYPRESS_ONEPWD_SERVICE_ACCOUNT_TOKEN }}
    with:
      cypress_brb: ${{ inputs.instance1 }}
      cypress_dbc: ${{ inputs.instance3 }}
      cypress_nbc: ${{ inputs.instance2 }}
      tag: cy:headless:stable:groupR:school_api_test:ci
      environment: ${{ needs.e2e-system-tests.outputs.environment }}
      groups: group-R

  run-tests-groupS:
    needs: e2e-system-tests
    uses: ./.github/workflows/main.yml
    secrets:
      service-account-token: ${{ secrets.CYPRESS_ONEPWD_SERVICE_ACCOUNT_TOKEN }}
    with:
      cypress_brb: ${{ inputs.instance1 }}
      cypress_dbc: ${{ inputs.instance3 }}
      cypress_nbc: ${{ inputs.instance2 }}
      tag: cy:headless:stable:groupS:school_api_test:ci
      environment: ${{ needs.e2e-system-tests.outputs.environment }}
      groups: group-S

  run-tests-groupT:
    needs: e2e-system-tests
    uses: ./.github/workflows/main.yml
    secrets:
      service-account-token: ${{ secrets.CYPRESS_ONEPWD_SERVICE_ACCOUNT_TOKEN }}
    with:
      cypress_brb: ${{ inputs.instance1 }}
      cypress_dbc: ${{ inputs.instance3 }}
      cypress_nbc: ${{ inputs.instance2 }}
      tag: cy:headless:stable:groupT:school_api_test:ci
      environment: ${{ needs.e2e-system-tests.outputs.environment }}
      groups: group-T

  notify_RC:
    runs-on: ubuntu-latest
    needs:
      - e2e-system-tests
      - run-tests-groupA
      - run-tests-groupB
      - run-tests-groupC
      - run-tests-groupD
      - run-tests-groupE
      - run-tests-groupF
      - run-tests-groupG
      - run-tests-groupH
      - run-tests-groupI
      - run-tests-groupJ
      - run-tests-groupK
      - run-tests-groupL
      - run-tests-groupM
      - run-tests-groupN
      - run-tests-groupO
      - run-tests-groupP
      - run-tests-groupQ
      - run-tests-groupR
      - run-tests-groupS
      - run-tests-groupT
    if: |
      always()

    steps:
      - uses: technote-space/workflow-conclusion-action@v3

      - name: Send Notification to Rocket Chat
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@1.1.1
        with:
          type: ${{ env.WORKFLOW_CONCLUSION }}
          job_name: "Cypress Tests"
          url: ${{ secrets.RC_WEBHOOK_URL }}
          username: Scheduled Trigger Test Run
