name: e2e-scheduled-trigger-tests
on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  e2e-system-tests:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set_variables.outputs.environment }}
      all_tests_tag: ${{ steps.set_variables.outputs.all_tests_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set environment and tags
        id: set_variables
        run: |
          # since this is scheduled, environment is always dev
          env_type="dev"
          all_tests_tag="@stable_test and @school_api_test"

          echo "environment=$env_type" >> $GITHUB_OUTPUT
          echo "all_tests_tag=$all_tests_tag" >> $GITHUB_OUTPUT

  run-scheduled-tests:
    needs: e2e-system-tests
    uses: ./.github/workflows/main.yml
    secrets:
      service-account-token: ${{ secrets.CYPRESS_ONEPWD_SERVICE_ACCOUNT_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - group: group-A
            browser: chrome
          - group: group-B
            browser: chrome
          - group: group-C
            browser: chrome
          - group: group-D
            browser: chrome
          - group: group-E
            browser: chrome
          - group: group-F
            browser: electron
    with:
      cypress_brb: https://main.brb.dbildungscloud.dev
      cypress_dbc: https://main.dbc.dbildungscloud.dev
      cypress_nbc: https://main.nbc.dbildungscloud.dev
      browser: ${{ matrix.browser }}
      tag: ${{ format('"{0} and @{1}"', needs.e2e-system-tests.outputs.all_tests_tag, matrix.group) }}
      environment: ${{ needs.e2e-system-tests.outputs.environment }}
      groups: ${{ format('{0}-{1}', 'scheduled-trigger-regression-tests', matrix.group) }}

  notify_RC:
    runs-on: ubuntu-latest
    needs: run-scheduled-tests
    if: always()
    steps:
      - uses: technote-space/workflow-conclusion-action@v3

      - name: Send Notification to Rocket Chat
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@1.1.1
        with:
          type: ${{ env.WORKFLOW_CONCLUSION }}
          job_name: "Cypress Tests"
          url: ${{ secrets.RC_WEBHOOK_URL }}
          username: Scheduled Trigger Test Run
