name: e2e-scheduled-trigger-tests
on:
  schedule:
    - cron: "0 1 * * *"
jobs:
  e2e-system-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Checkout
        uses: actions/checkout@v4

  configuring-loading-secrets-running-tests:
    needs: e2e-system-tests
    uses: ./.github/workflows/main.yml
    secrets:
      service-account-token: ${{ secrets.CYPRESS_ONEPWD_SERVICE_ACCOUNT_TOKEN }}
    with:
      cypress_brb: https://main.brb.dbildungscloud.dev
      cypress_dbc: https://main.dbc.dbildungscloud.dev
      cypress_nbc: https://main.nbc.dbildungscloud.dev
      tag: cy:headless:stable:schedule_run:school_api_test:ci
      environment: dev
      groups: scheduled

  run-tests-groupA:
    needs: e2e-system-tests
    uses: ./.github/workflows/main.yml
    secrets:
      service-account-token: ${{ secrets.CYPRESS_ONEPWD_SERVICE_ACCOUNT_TOKEN }}
    with:
      cypress_brb: ${{ inputs.instance1 }}
      cypress_dbc: ${{ inputs.instance3 }}
      cypress_nbc: ${{ inputs.instance2 }}
      tag: cy:headless:stable:groupA:school_api_test:ci
      environment: ${{ needs.e2e-system-tests.outputs.environment }}
      groups: group-A

  run-tests-groupB:
    needs: e2e-system-tests
    uses: ./.github/workflows/main.yml
    secrets:
      service-account-token: ${{ secrets.CYPRESS_ONEPWD_SERVICE_ACCOUNT_TOKEN }}
    with:
      cypress_brb: ${{ inputs.instance1 }}
      cypress_dbc: ${{ inputs.instance3 }}
      cypress_nbc: ${{ inputs.instance2 }}
      tag: cy:headless:stable:groupB:school_api_test:ci
      environment: ${{ needs.e2e-system-tests.outputs.environment }}
      groups: group-B

  notify_RC:
    runs-on: ubuntu-latest
    needs:
      - e2e-system-tests
      - configuring-loading-secrets-running-tests
    if: |
      always()

    steps:
      - uses: technote-space/workflow-conclusion-action@v3

      - name: Send Notification to Rocket Chat
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@1.1.1
        with:
          type: ${{ env.WORKFLOW_CONCLUSION }}
          job_name: "Cypress Tests"
          url: ${{ secrets.RC_WEBHOOK_URL }}
          username: Scheduled Trigger Test Run
